name: Cleanup Old Workflow Runs
on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次，您可以根据需要调整时间
  workflow_dispatch: # 允许手动触发
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Delete old successful workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.repository }}
        num_workflow_runs_to_keep: 3
        status: success # 仅删除成功的运行
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 确保您有一个 GitHub Token
