name: Update GitHub520.plugin

on:
  schedule:
    - cron: '0 1/3 * * *' # 从UTC时间1点开始，每三小时执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
