name: Update /GitHub520.plugin

on:
  schedule:
    - cron: '0 0 * * *' # 每天零点执行一次（UTC时间）
  workflow_dispatch: # 手动触发选项

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
     contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch hosts.txt
      run: |
        curl --retry 5 --retry-delay 5 -o GitHub520.plugin https://hosts.gitcdn.top/hosts.txt

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add GitHub520.plugin
        git commit -m "Update GitHub520.plugin from hosts.gitcdn.top" || echo "No changes to commit"
        git push
