name: Update GitHub520.plugin
on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch: # 手动触发
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download hosts file
      run: wget -q -O hosts.txt https://hosts.gitcdn.top/hosts.txt
    - name: Process the file
      run: |
        # 处理文件，根据要求修改内容
        awk '/^#/ {next} {print $2, $1}' hosts.txt | sed 's/ / = /' > GitHub520.plugin
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add GitHub520.plugin
        git commit -m "Update GitHub520.plugin"
        git push
