name: Update DIRECT.yaml
on:
  push:
  workflow_dispatch:  # 手动触发
    paths:
      - CMJ781/Loon/DIRECT.list
jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Process DIRECT.list
      run: |
        # 处理文件
        awk '!/^#/{print "  - "$0}' CMJ781/Loon/DIRECT.list > CMJ781/Loon/Clash/DIRECT.yaml
        
        # 在文件开头插入"payload:"
        sed -i '1ipayload:' CMJ781/Loon/Clash/DIRECT.yaml
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add Clash/DIRECT.yaml
        git commit -m "Update DIRECT.yaml based on changes in DIRECT.list"
        git push
