name: Update DIRECT.yaml
on:
  push:
    paths:
      - 'Loon/DIRECT.list'
  workflow_dispatch:  # 添加手动触发功能
jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Download DIRECT.list
      run: |
        # 下载文件到本地
        curl -o Loon/DIRECT.list https://raw.githubusercontent.com/CMJ781/Loon/refs/heads/main/DIRECT.list
    - name: Process DIRECT.list
      run: |
        # 创建Clash文件夹
        mkdir -p Clash
        
        # 处理文件
        awk '!/^#/{print "  - "$0}' Loon/DIRECT.list > Clash/DIRECT.yaml
        
        # 在文件开头插入"payload:"
        sed -i '1ipayload:' Clash/DIRECT.yaml
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add Clash/DIRECT.yaml
        git commit -m "Update DIRECT.yaml based on changes in DIRECT.list"
        git push
