name: Update DIRECT.yaml
on:
  push:
    paths:
      - 'DIRECT.list'
  workflow_dispatch:
jobs:
  process-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Process DIRECT.list
      run: |
        # 确保在仓库的根目录下
        cd $GITHUB_WORKSPACE
        # 创建Loon/Clash文件夹
        mkdir -p Loon/Clash
        
        # 处理文件
        awk '!/^#/{print "  - "$0}' DIRECT.list > Clash/DIRECT.yaml
        
        # 在文件开头插入"payload:"
        sed -i '1ipayload:' Clash/DIRECT.yaml
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Clash/DIRECT.yaml
        git commit -m "Update Clash/DIRECT.yaml"
        git push

  cleanup:
    runs-on: ubuntu-22.04  # 指定 Ubuntu 版本

    steps:
    - name: Delete old successful workflow runs
      uses: actions/github-script@v7  # 更新到支持 Node.js 20 的版本
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: workflows } = await github.rest.actions.listRepoWorkflows({
            owner: context.repo.owner,
            repo: context.repo.repo
          });

          const workflow = workflows.workflows.find(wf => wf.name === 'Update GitHub520.plugin');
          if (!workflow) {
            throw new Error('Workflow not found');
          }

          const { data: workflowRuns } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: workflow.id,
            per_page: 100
          });

          const successfulRuns = workflowRuns.workflow_runs.filter(run => run.conclusion === 'success');
          const runsToDelete = successfulRuns.slice(1); // 保留最近1个成功运行记录

          for (const run of runsToDelete) {
            await github.rest.actions.deleteWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run.id
            });
          }
